[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:ia]
command=/bin/sh -lc "export IA_PORT=5005; cd /app/ia && python3 ia_fastapi2_0.py"
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:backend]
command=/bin/sh -lc "java $JAVA_OPTS -jar /app/backend/app.jar --server.port=8080"
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

[program:nginx]
command=/bin/sh -lc "nginx -g 'daemon off;'"
autorestart=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0

